name: Reusable test matrix generation

on:
  workflow_call:
    inputs:
      intel_drivers_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2204_intel_drivers:latest"
      amdgpu_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2204_build:latest"
      cuda_image:
        type: string
        required: false
        default: "ghcr.io/intel/llvm/ubuntu2204_build:latest"
      e2e_config:
        type: string
        required: true
        default: ""
      cts_config:
        type: string
        required: false
        default: ""
      uniq:
        description: Unique string to name dynamic runners in AWS
        type: string
        required: false
        default: ${{ github.run_id }}-${{ github.run_attempt }}
      ref:
        description: "Commit to use for checkout or github.sha by default"
        type: string
        required: false
        default: ${{ github.sha }}
    outputs:
      e2e_lx_matrix:
        description: "Linux E2E"
        value: ${{ jobs.test_matrix.outputs.e2e_lx_matrix }}
      e2e_wn_matrix:
        description: "Windows E2E"
        value: ${{ jobs.test_matrix.outputs.e2e_wn_matrix }}
      cts_matrix:
        description: "SYCL CTS"
        value: ${{ jobs.test_matrix.outputs.cts_matrix }}
      e2e_aws_matrix:
        description: "Linux AWS"
        value: ${{ jobs.test_matrix.outputs.e2e_aws_matrix }}
jobs:
  test_matrix:
    name: Generate Test Matrix
    runs-on: ubuntu-20.04
    outputs:
      e2e_lx_matrix: ${{ steps.work.outputs.e2e_lx_matrix }}
      e2e_wn_matrix: ${{ steps.work.outputs.e2e_wn_matrix }}
      cts_matrix: ${{ steps.work.outputs.cts_matrix }}
      e2e_aws_matrix: ${{ steps.work.outputs.e2e_aws_matrix }}
    steps:
    - name: Download scripts and configs
      shell: bash
      run: |
        wget raw.githubusercontent.com/intel/llvm/${{ inputs.ref }}/devops/scripts/generate_test_matrix.js
        wget raw.githubusercontent.com/intel/llvm/${{ inputs.ref }}/devops/test_configs.json
        wget raw.githubusercontent.com/intel/llvm/sycl/devops/dependencies.json
        mv dependencies.json dependencies.sycl.json
        wget raw.githubusercontent.com/intel/llvm/${{ inputs.ref }}/devops/dependencies.json
    - id: work
      uses: actions/github-script@v6
      name: Generate matrix
      env:
        GHA_INPUTS: ${{ toJSON(inputs) }}
      with:
        script: |
          const script = require('./generate_test_matrix.js');
          script({core, process});
